name: .NET logging library test

on:
  [push, pull_request]

jobs:
  test-execution:
    runs-on: windows-latest
    strategy:
      matrix:
        splunk-version:
          - "8.0"
    steps:
    - uses: actions/checkout@v2
    - name: Start splunk container
      uses: make up
